<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Documents/Types/DocumentTypeDescription.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Documents\Types;

/**
 * Protobuf enum :
 * AgentSIB.Diadoc.Api.Proto.Documents.Types.DocumentMetadataItemType
 */
class DocumentMetadataItemType extends \Protobuf\Enum
{

    /**
     * String = 0
     */
    const String_VALUE = 0;

    /**
     * Integer = 1
     */
    const Integer_VALUE = 1;

    /**
     * Decimal = 2
     */
    const Decimal_VALUE = 2;

    /**
     * Date = 3
     */
    const Date_VALUE = 3;

    /**
     * Time = 4
     */
    const Time_VALUE = 4;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    protected static $String = null;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    protected static $Integer = null;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    protected static $Decimal = null;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    protected static $Date = null;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    protected static $Time = null;

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    public static function String()
    {
        if (self::$String !== null) {
            return self::$String;
        }

        return self::$String = new self('String', self::String_VALUE);
    }

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    public static function Integer()
    {
        if (self::$Integer !== null) {
            return self::$Integer;
        }

        return self::$Integer = new self('Integer', self::Integer_VALUE);
    }

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    public static function Decimal()
    {
        if (self::$Decimal !== null) {
            return self::$Decimal;
        }

        return self::$Decimal = new self('Decimal', self::Decimal_VALUE);
    }

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    public static function Date()
    {
        if (self::$Date !== null) {
            return self::$Date;
        }

        return self::$Date = new self('Date', self::Date_VALUE);
    }

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    public static function Time()
    {
        if (self::$Time !== null) {
            return self::$Time;
        }

        return self::$Time = new self('Time', self::Time_VALUE);
    }

    /**
     * @param int $value
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataItemType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::String();
            case 1: return self::Integer();
            case 2: return self::Decimal();
            case 3: return self::Date();
            case 4: return self::Time();
            default: return null;
        }
    }


}

