<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Documents/Types/DocumentTypeDescription.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Documents\Types;

/**
 * Protobuf enum : AgentSIB.Diadoc.Api.Proto.Documents.Types.DocumentDocflow
 */
class DocumentDocflow extends \Protobuf\Enum
{

    /**
     * External = 0
     */
    const External_VALUE = 0;

    /**
     * Internal = 1
     */
    const Internal_VALUE = 1;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentDocflow
     */
    protected static $External = null;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentDocflow
     */
    protected static $Internal = null;

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentDocflow
     */
    public static function External()
    {
        if (self::$External !== null) {
            return self::$External;
        }

        return self::$External = new self('External', self::External_VALUE);
    }

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentDocflow
     */
    public static function Internal()
    {
        if (self::$Internal !== null) {
            return self::$Internal;
        }

        return self::$Internal = new self('Internal', self::Internal_VALUE);
    }

    /**
     * @param int $value
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentDocflow
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::External();
            case 1: return self::Internal();
            default: return null;
        }
    }


}

