<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Documents/Types/DocumentTypeDescription.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Documents\Types;

/**
 * Protobuf enum : AgentSIB.Diadoc.Api.Proto.Documents.Types.DocumentMetadataSource
 */
class DocumentMetadataSource extends \Protobuf\Enum
{

    /**
     * Xml = 0
     */
    const Xml_VALUE = 0;

    /**
     * User = 1
     */
    const User_VALUE = 1;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataSource
     */
    protected static $Xml = null;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataSource
     */
    protected static $User = null;

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataSource
     */
    public static function Xml()
    {
        if (self::$Xml !== null) {
            return self::$Xml;
        }

        return self::$Xml = new self('Xml', self::Xml_VALUE);
    }

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataSource
     */
    public static function User()
    {
        if (self::$User !== null) {
            return self::$User;
        }

        return self::$User = new self('User', self::User_VALUE);
    }

    /**
     * @param int $value
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\DocumentMetadataSource
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::Xml();
            case 1: return self::User();
            default: return null;
        }
    }


}

