<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Documents/Types/DocumentTypeDescription.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Documents\Types;

/**
 * Protobuf enum : AgentSIB.Diadoc.Api.Proto.Documents.Types.SignerType
 */
class SignerType extends \Protobuf\Enum
{

    /**
     * None = 0
     */
    const None_VALUE = 0;

    /**
     * Signer = 1
     */
    const Signer_VALUE = 1;

    /**
     * ExtendedSigner = 2
     */
    const ExtendedSigner_VALUE = 2;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType
     */
    protected static $None = null;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType
     */
    protected static $Signer = null;

    /**
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType
     */
    protected static $ExtendedSigner = null;

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType
     */
    public static function None()
    {
        if (self::$None !== null) {
            return self::$None;
        }

        return self::$None = new self('None', self::None_VALUE);
    }

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType
     */
    public static function Signer()
    {
        if (self::$Signer !== null) {
            return self::$Signer;
        }

        return self::$Signer = new self('Signer', self::Signer_VALUE);
    }

    /**
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType
     */
    public static function ExtendedSigner()
    {
        if (self::$ExtendedSigner !== null) {
            return self::$ExtendedSigner;
        }

        return self::$ExtendedSigner = new self('ExtendedSigner', self::ExtendedSigner_VALUE);
    }

    /**
     * @param int $value
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::None();
            case 1: return self::Signer();
            case 2: return self::ExtendedSigner();
            default: return null;
        }
    }


}

