<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : Documents/Types/DocumentTypeDescription.proto
 */


namespace AgentSIB\Diadoc\Api\Proto\Documents\Types;

/**
 * Protobuf message : AgentSIB.Diadoc.Api.Proto.Documents.Types.SignerInfo
 */
class SignerInfo extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * SignerType required enum = 1
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType
     */
    protected $SignerType = null;

    /**
     * ExtendedDocumentTitleType required enum = 2
     *
     * @var \AgentSIB\Diadoc\Api\Proto\Invoicing\Signers\DocumentTitleType
     */
    protected $ExtendedDocumentTitleType = null;

    /**
     * {@inheritdoc}
     */
    public function __construct($stream = null, \Protobuf\Configuration $configuration = null)
    {
        $this->ExtendedDocumentTitleType = \AgentSIB\Diadoc\Api\Proto\Invoicing\Signers\DocumentTitleType::Absent();

        parent::__construct($stream, $configuration);
    }

    /**
     * Check if 'SignerType' has a value
     *
     * @return bool
     */
    public function hasSignerType()
    {
        return $this->SignerType !== null;
    }

    /**
     * Get 'SignerType' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType
     */
    public function getSignerType()
    {
        return $this->SignerType;
    }

    /**
     * Set 'SignerType' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType $value
     */
    public function setSignerType(\AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType $value)
    {
        $this->SignerType = $value;
    }

    /**
     * Check if 'ExtendedDocumentTitleType' has a value
     *
     * @return bool
     */
    public function hasExtendedDocumentTitleType()
    {
        return $this->ExtendedDocumentTitleType !== null;
    }

    /**
     * Get 'ExtendedDocumentTitleType' value
     *
     * @return \AgentSIB\Diadoc\Api\Proto\Invoicing\Signers\DocumentTitleType
     */
    public function getExtendedDocumentTitleType()
    {
        return $this->ExtendedDocumentTitleType;
    }

    /**
     * Set 'ExtendedDocumentTitleType' value
     *
     * @param \AgentSIB\Diadoc\Api\Proto\Invoicing\Signers\DocumentTitleType $value
     */
    public function setExtendedDocumentTitleType(\AgentSIB\Diadoc\Api\Proto\Invoicing\Signers\DocumentTitleType $value)
    {
        $this->ExtendedDocumentTitleType = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['SignerType'])) {
            throw new \InvalidArgumentException('Field "SignerType" (tag 1) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
        ], $values);

        $message->setSignerType($values['SignerType']);
        $message->setExtendedDocumentTitleType($values['ExtendedDocumentTitleType']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'SignerInfo',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'SignerType',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Documents.Types.SignerType'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'ExtendedDocumentTitleType',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_ENUM(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED(),
                    'type_name' => '.AgentSIB.Diadoc.Api.Proto.Invoicing.Signers.DocumentTitleType',
                    'default_value' => \AgentSIB\Diadoc\Api\Proto\Invoicing\Signers\DocumentTitleType::Absent()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->SignerType === null) {
            throw new \UnexpectedValueException('Field "\\AgentSIB\\Diadoc\\Api\\Proto\\Documents\\Types\\SignerInfo#SignerType" (tag 1) is required but has no value.');
        }

        if ($this->ExtendedDocumentTitleType === null) {
            throw new \UnexpectedValueException('Field "\\AgentSIB\\Diadoc\\Api\\Proto\\Documents\\Types\\SignerInfo#ExtendedDocumentTitleType" (tag 2) is required but has no value.');
        }

        if ($this->SignerType !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->SignerType->value());
        }

        if ($this->ExtendedDocumentTitleType !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->ExtendedDocumentTitleType->value());
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->SignerType = \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerType::valueOf($reader->readVarint($stream));

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 14);

                $this->ExtendedDocumentTitleType = \AgentSIB\Diadoc\Api\Proto\Invoicing\Signers\DocumentTitleType::valueOf($reader->readVarint($stream));

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->SignerType !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->SignerType->value());
        }

        if ($this->ExtendedDocumentTitleType !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->ExtendedDocumentTitleType->value());
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->SignerType = null;
        $this->ExtendedDocumentTitleType = \AgentSIB\Diadoc\Api\Proto\Invoicing\Signers\DocumentTitleType::Absent();
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \AgentSIB\Diadoc\Api\Proto\Documents\Types\SignerInfo) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->SignerType = ($message->SignerType !== null) ? $message->SignerType : $this->SignerType;
        $this->ExtendedDocumentTitleType = ($message->ExtendedDocumentTitleType !== null) ? $message->ExtendedDocumentTitleType : $this->ExtendedDocumentTitleType;
    }


}

